name: CI and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/wf-nix-ci.yml

  deploy:
    needs: [ci]
    uses: ./.github/workflows/wf-deploy.yml
