name: Nix CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Check flake
        run: nix flake check --all-systems --no-build

      - name: Build chlorine system
        run: nix build .#nixosConfigurations.chlorine.config.system.build.toplevel
